language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
env:
    - TEST_DIR=tasks/001
    - TEST_DIR=tasks/002
    - TEST_DIR=tasks/003
# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: cd $TEST_DIR && phpunit test
